sudo: required
dist: trusty

language: haxe

os:
  - linux
  
haxe:
  - "3.2.1"
  - development
      
install:
  - haxelib install travix
  - haxelib install tink_hxx
  - haxelib run travix install

script:
  - haxelib run travix js
  - haxelib run travix js -lib tink_hxx
